### ISSUE TITLE
First run mess

### ISSUE THREAD

**Issue by tigger04** [I60R/page#18]
Just installed the mac binary,

ls | page gives me:

```
thread 'main' panicked at 'Cannot open page PTY: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/page.rs:353:48
[Process exited 1]                                  note: run with `RUST_BACKTRACE=1`environment variable to display a backtrace
                                           ❌ exit code: 101
                                                            🔸~/Downloads$
```

with RUST_BACKTRACE=1:

```
[?1049h[22;0t[?1h=[H[2J]11;?[?2004h[?25hVim: Error reading input, exiting...

[?25l(B[m[H[2J[H[2J[K
[94m~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
~[K
(B[m[93m[104m[No Name][53X[53C1,0-1          All]112[2 q]112[2 q[H[?25hVim: Finished.
[?25l[23B[?25h[?25l]112[2 q(B[m[?25h[?1l>[?1049l[23;0t[?2004l[?1004l[?25hthread 'main' panicked at 'Error sending message: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/neovim-lib-0.6.1/src/rpc/client.rs:188:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::option::expect_none_failed
   8: neovim_lib::rpc::client::Client<R,W>::send_msg
   9: neovim_lib::session::Session::call
  10: <neovim_lib::neovim::Neovim as neovim_lib::neovim_api::NeovimApi>::subscribe
  11: page::main
  12: std::rt::lang_start::{{closure}}
  13: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by I60R** [comment]
I'm currently working on next release where this issue should be fixed. As for now you could compile `next_release` branch to test if it's fixed for you (or just wait for a next release — if everything would be okay should happen on the next month).

**Comment by I60R** [comment]
Finally it's published.

Version 3.0.0 should work fine. Feel free to reopen this issue if there's something wrong
